### PR TITLE
Fix ckeditor

### LINKED ISSUE #89: Readd CKeditor integration
This is now lost in the StaticContent admin.

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
fixes #89 

ToDo:

* [x] See it working on sandbox

### CODE REVIEW

File: src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php [hunk 1]
```diff
@@ -61,6 +64,34 @@ public function load(array $configs, ContainerBuilder $container)
...
+    {
+        $container->setParameter('cmf_sonata_phpcr_admin_integration.ivory_ckeditor.config', []);
+        $bundles = $container->getParameter('kernel.bundles');
+        if ('auto' === $config['enabled'] && !isset($bundles['IvoryCKEditorBundle'])) {
+            return;
+        }
+
+        if ($this->isConfigEnabled($container, $config) && !isset($bundles['IvoryCKEditorBundle'])) {
+            $message = 'IvoryCKEditorBundle integration was explicitely enabled, but the bundle is not available';
+            if (class_exists('Ivory\CKEditorBundle\IvoryCKEditorBundle')) {
```
Comment (dbu) [inline src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php]: use ::class constant. works even when class is not definde

File: composer.json [hunk 2]
```diff
@@ -16,7 +16,8 @@
         "symfony/framework-bundle": "^2.8|^3.0",
         "sonata-project/doctrine-phpcr-admin-bundle": "^2.0",
         "sonata-project/admin-bundle": "^3.6.0",
-        "symfony-cmf/tree-browser-bundle": "^2.0"
+        "symfony-cmf/tree-browser-bundle": "^2.0",
+        "egeloen/ckeditor-bundle": "^4.0"
```
Comment (dbu) [inline composer.json]: i am fine with making this a hard dependency. but do we still need the class-exists checks below then? or should this be a require-dev?

File: src/Admin/Content/StaticContentAdmin.php [hunk 3]
```diff
@@ -11,22 +11,33 @@
...
+     */
+    private $ckEditorConfig;
+
     public function getExportFormats()
     {
-        return array();
+        return [];
+    }
+
+    public function setCkEditorConfig($config)
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: please add a phpdoc that tells where to find doc for the options (i assume in the formtype doc of ck bundle?)

File: src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php [hunk 4]
```diff
@@ -61,6 +64,34 @@ public function load(array $configs, ContainerBuilder $container)
 
         $loader->load('main.xml');
         $loader->load('enhancer.xml');
+
+        $this->loadIvoryCKEditor($config['ivory_ckeditor'], $container);
+    }
+
+    protected function loadIvoryCKEditor(array $config, ContainerBuilder $container)
+    {
+        $container->setParameter('cmf_sonata_phpcr_admin_integration.ivory_ckeditor.config', []);
```
Comment (dbu) [inline src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php]: i'd rather do 'if $this->isConfigEnabled... else setParameter []' in the main method

File: src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php (hunk 1 above)
Comment (ElectricMaxxx) [inline src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php]: ok, didn't know that it works.

File: composer.json (hunk 2 above)
Comment (ElectricMaxxx) [inline composer.json]: mhh .. can be on dev and into suggested then. The version comes by a simple `composer require` call.

Comment (dbu) [inline composer.json]: ok, then lets move it there to make ckeditor really optional.

File: src/DependencyInjection/Configuration.php [hunk 5]
```diff
@@ -41,6 +41,17 @@ public function getConfigTreeBuilder()
 
         $this->addBundlesSection($root);
 
+        $root
+            ->children()
+                ->arrayNode('ivory_ckeditor')
+                    ->addDefaultsIfNotSet()
+                    ->canBeEnabled()
+                    ->children()
+                        ->scalarNode('config_name')->defaultValue('cmf_sonata_phpcr_admin_integration')->end()
```
Comment (dbu) [inline src/DependencyInjection/Configuration.php]: is this configuration defined somewhere? afaik it needs to be in some template so that javascript can see it when initializing ckeditor? or is that part still in, but we lost the configuration option?

File: src/DependencyInjection/Configuration.php [hunk 6]
```diff
@@ -41,6 +41,17 @@ public function getConfigTreeBuilder()
 
         $this->addBundlesSection($root);
 
+        $root
+            ->children()
+                ->arrayNode('ivory_ckeditor')
+                    ->addDefaultsIfNotSet()
+                    ->canBeEnabled()
```
Comment (dbu) [inline src/DependencyInjection/Configuration.php]: if you use this, there is no 'auto' but only true/false. see for example https://github.com/symfony-cmf/menu-bundle/blob/eb754e913e96a9fa19637bbbf86358cb86df5d54/src/DependencyInjection/Configuration.php#L63-L66

File: src/DependencyInjection/Configuration.php (hunk 5 above)
Comment (ElectricMaxxx) [inline src/DependencyInjection/Configuration.php]: The only think we use in here is a key. That key referes to a configuration on IvoryCkEditorBundle. You see it in a WIP PR on sandbox to use this one here (tried it local with this branch): https://github.com/symfony-cmf/cmf-sandbox/pull/363

File: src/DependencyInjection/Configuration.php (hunk 6 above)
Comment (ElectricMaxxx) [inline src/DependencyInjection/Configuration.php]: I copied from simple-cms-bundle, there was an auto and i removed it ;-) I will redo it.

File: src/DependencyInjection/Configuration.php (hunk 5 above)
Comment (dbu) [inline src/DependencyInjection/Configuration.php]: ah, ok. can you add a phpdoc about that to the admin classes where we set the option? we also must not forget to document that. can you add an issue in symfony-cmf/symfony-cmf-documentation please?

**Comment by ElectricMaxxx** [comment]
I also added a webtest on that theme. I would fix styling and squash, when you like it?

File: src/Admin/Content/StaticContentAdmin.php [hunk 7]
```diff
@@ -11,22 +11,40 @@
...
+    }
+
+    /**
+     * Configuration passed to the CKEditorType. Have a look at the docs:
+     *
+     * http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/config.html
+     *
+     * @param [] $config
+     */
+    public function setCkEditorConfig($config)
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: if this is an array, please typehint array

File: src/Admin/Content/StaticContentAdmin.php [hunk 8]
```diff
@@ -11,22 +11,40 @@
...
-use Symfony\Component\Form\Extension\Core\Type\TextType;
 use Symfony\Component\Form\Extension\Core\Type\TextareaType;
+use Symfony\Component\Form\Extension\Core\Type\TextType;
 
 class StaticContentAdmin extends AbstractAdmin
 {
     protected $translationDomain = 'CmfSonataPhpcrAdminIntegrationBundle';
 
+    /**
+     * @var []
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: please use string[] if this is a list of strings, or array if its a nested thing. if you can describe what it contains, all the better

File: src/Admin/Content/StaticContentAdmin.php [hunk 9]
```diff
@@ -11,22 +11,40 @@
...
-        return array();
+        return [];
+    }
+
+    /**
+     * Configuration passed to the CKEditorType. Have a look at the docs:
+     *
+     * http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/config.html
+     *
+     * @param [] $config
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: please fix the typehint here and explain what $config is

what are the options for the ckeditor type? does it have other options than config_name?

File: src/DependencyInjection/Configuration.php [hunk 10]
```diff
@@ -41,6 +41,20 @@ public function getConfigTreeBuilder()
...
+        $root
+            ->children()
+                ->arrayNode('ivory_ckeditor')
+                    ->addDefaultsIfNotSet()
+                    ->children()
+                        ->enumNode('enabled')
+                            ->values([true, false, 'auto'])
+                            ->defaultValue('auto')
+                        ->end()
+                        ->scalarNode('config_name')->defaultValue('cmf_sonata_phpcr_admin_integration')->end()
```
Comment (dbu) [inline src/DependencyInjection/Configuration.php]: is this configuration automatically defined? if not, i would not use a default value at all, and make config_name required instead.

**Comment by ElectricMaxxx** [comment]
@dbu as you can see in the [Docs](http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/config.html#override-a-configuration), you can pass an array containing  `config_name`, `config` or both as keys. When passing `config` into our admin by overiding the parameter or the admin defintion, you have full access to the [CkEdior Configuration](http://docs.ckeditor.com/#!/api/CKEDITOR.config). We have a configuration for the `config_name` only and i think this is enough. If somebody whants more he should override the parameter or the admin, or simply use the `config_name` option. But we have the door open to do it all without copying the configuration to ours.

File: src/Admin/Content/StaticContentAdmin.php [hunk 11]
```diff
@@ -11,22 +11,42 @@
...
+    private $ckEditorConfig;
+
     public function getExportFormats()
     {
-        return array();
+        return [];
+    }
+
+    /**
+     * Configuration passed to the CKEditorType. Have a look at the docs:
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: styleci complains. lets move "Have a look at the docs:" to a second section and do something like "The configuration array is explained in the IvoryCKEditorBundle documentation: http://"

**Comment by ElectricMaxxx** [comment]
looks better now. Github suggested to solve a conflict with master and did a merge of master then. But i rebased localy and forced pushed

**Comment by ElectricMaxxx** [comment]
seems as styleCI also works (currently not) on AWS.

**Comment by ElectricMaxxx** [comment]
I squasched, ready to merge from my POV.

File: src/Resources/config/schema/sonata-phpcr-admin-integration.xsd [hunk 12]
```diff
@@ -18,4 +19,8 @@
         </xsd:sequence>
     </xsd:complexType>
 
+    <xsd:complexType name="ivory_ckeditor">
+        <xsd:attribute name="config_name" type="xsd:string"/>
```
Comment (dbu) [inline src/Resources/config/schema/sonata-phpcr-admin-integration.xsd]: i think this is missing the enabled flag

File: src/Admin/Content/StaticContentAdmin.php [hunk 13]
```diff
@@ -11,22 +11,41 @@
...
+    private $ckEditorConfig;
+
     public function getExportFormats()
     {
-        return array();
+        return [];
+    }
+
+    /**
+     * The configuration array is explained in the IvoryCKEditorBundle
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: i was suggesting this as a second section of the phpdoc - styleci is still not happy with this (i restarted it now that aws works again)

i would keep the first line as "Set configuration for CKEditorType." or something like that

File: src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php [hunk 14]
```diff
@@ -73,10 +73,10 @@ public function load(array $configs, ContainerBuilder $container)
      * Adds the ckEditor configuration to the parameters list when configuration is enabled (auto, true). For both
      * settings the "egeloen/ckeditor-bundle" has to be installed and enabled.
      *
-     * @param [] $config
+     * @param []               $config
```
Comment (dbu) [inline src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php]: this should say array, not `[]`

File: src/Admin/Content/StaticContentAdmin.php [hunk 15]
```diff
@@ -11,22 +11,42 @@
...
+use Symfony\Component\Form\Extension\Core\Type\TextType;
 
 class StaticContentAdmin extends AbstractAdmin
 {
     protected $translationDomain = 'CmfSonataPhpcrAdminIntegrationBundle';
 
+    /**
+     * Configuration, that can be passed to CKEditorType.
+     *
+     * @var []
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: this should say array, not []

File: src/Admin/Content/StaticContentAdmin.php [hunk 16]
```diff
@@ -11,22 +11,42 @@
...
-        return array();
+        return [];
+    }
+
+    /**
+     * Set configuration for CKEditorType.
+     *
+     * Documentation: http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/config.html
+     *
+     * @param [] $config configuration for CKEditorType
```
Comment (dbu) [inline src/Admin/Content/StaticContentAdmin.php]: this should say array not []

File: src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php [hunk 17]
```diff
@@ -61,6 +65,36 @@ public function load(array $configs, ContainerBuilder $container)
...
         $loader->load('enhancer.xml');
+
+        $this->loadIvoryCKEditor($config['ivory_ckeditor'], $container);
+    }
+
+    /**
+     * Adds the ckEditor configuration to the parameters list when configuration is enabled (auto, true). For both
+     * settings the "egeloen/ckeditor-bundle" has to be installed and enabled.
+     *
+     * @param []               $config
```
Comment (dbu) [inline src/DependencyInjection/CmfSonataPhpcrAdminIntegrationExtension.php]: this should also say array

**Comment by ElectricMaxxx** [comment]
@dbu you have got an idea on the one failing [job](https://travis-ci.org/symfony-cmf/sonata-phpcr-admin-integration-bundle/jobs/206564437)? Looks very strange.

**Comment by dbu** [comment]
this looks a lot like we allow too old versions of some package. probably not related to your PR. i restarted the last master test https://travis-ci.org/symfony-cmf/sonata-phpcr-admin-integration-bundle/builds/205041731

**Comment by dbu** [comment]
yep, not related to this PR. merged this one. thanks a lot! i will try to see what is wrong with the lowest version build

File: src/Admin/Content/StaticContentAdmin.php [hunk 18]
```diff
@@ -11,22 +11,42 @@
...
 class StaticContentAdmin extends AbstractAdmin
 {
     protected $translationDomain = 'CmfSonataPhpcrAdminIntegrationBundle';
 
+    /**
+     * Configuration, that can be passed to CKEditorType.
+     *
+     * @var array
+     */
+    private $ckEditorConfig;
```
Comment (wouterj) [inline src/Admin/Content/StaticContentAdmin.php]: `@var array`, so this should be `= [];`

File: tests/Resources/Fixtures/config/config.xml [hunk 19]
```diff
@@ -7,5 +7,6 @@
         <bundles>
             <seo enabled="true" />
         </bundles>
+        <ivory_ckeditor config_name="cmf_sonata_phpcr_admin_integration" />
```
Comment (wouterj) [inline tests/Resources/Fixtures/config/config.xml]: `ivory-ckeditor`  and `config-name`

**Comment by dbu** [comment]
sorry, seems i was too fast with merging. good we did not tag any
version with this.

> I'm not totally sure if it should be global or factory specific. E.g.
> you might want another editor config for a page than for a simple static
> content.

for the moment we only have a single admin with wysiwyg. but indeed, we
should better move the configuration to the content admin. right now it
makes no difference, and if we add more admins that need it, we can
introduce a global default and keep the specific config, without that
being a BC break.

the "enabled" part is not needed anymore actually. there is no default
configuration anymore, so the field can just either be set or not.

max, can you do a follow-up PR to clean this up, or shall i do it?

File: tests/Resources/Fixtures/config/config.xml (hunk 19 above)
Comment (ElectricMaxxx) [inline tests/Resources/Fixtures/config/config.xml]: and the auto-change in the `Configuration`, right?

**Comment by ElectricMaxxx** [comment]
> I'm not totally sure if it should be global or factory specific. E.g. you might want another editor config for a page than for a simple static content.

If you have in mint to allow different WYSWING editors i would suggest a configuration like:

```yml
cmf_sonata_phpcr_admin_integration:
    wyswing:
       ivory_ckeditor:
           config_name: "bla"
       some_other:
           some_more_config: "blubb"
``` 

combined with the posibility to override or inherit in a specic bundle/admin.
